remote_theme: pages-themes/dinky@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: [Decoding the Dataverse]
description: [Analytics to Illustrations]
show_downloads: ["false"]

linkedin_url: "https://www.linkedin.com/in/rupa-kanchi-8428982b/"
x_url: "https://x.com/rupakanchi"